//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bay_view_hotel_booking_system.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("bay_view_hotel_booking_system.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon bay_view_icon {
            get {
                object obj = ResourceManager.GetObject("bay_view_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bay_view_logo {
            get {
                object obj = ResourceManager.GetObject("bay_view_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEGIN TRANSACTION;
        ///DROP TABLE IF EXISTS &quot;Payment&quot;;
        ///CREATE TABLE IF NOT EXISTS &quot;Payment&quot; (
        ///	&quot;PaymentID&quot;	INTEGER NOT NULL,
        ///	&quot;BookingID&quot;	INTEGER NOT NULL,
        ///	&quot;Amount&quot;	REAL NOT NULL,
        ///	FOREIGN KEY(&quot;BookingID&quot;) REFERENCES &quot;Booking&quot;(&quot;BookingID&quot;),
        ///	PRIMARY KEY(&quot;PaymentID&quot; AUTOINCREMENT)
        ///);
        ///DROP TABLE IF EXISTS &quot;Booking&quot;;
        ///CREATE TABLE IF NOT EXISTS &quot;Booking&quot; (
        ///	&quot;BookingID&quot;	INTEGER NOT NULL,
        ///	&quot;CustomerID&quot;	INTEGER NOT NULL,
        ///	&quot;RoomID&quot;	INTEGER NOT NULL,
        ///	&quot;StartDate&quot;	TEXT NOT NULL,
        ///	&quot;EndDate&quot;	TEXT NOT NULL,        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bayview_setup_empty {
            get {
                return ResourceManager.GetString("bayview_setup_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM Customer
        ///WHERE CustomerID != 1;
        ///
        ///INSERT INTO Customer (CustomerID, Forename, Surname, PhoneNumber, Email)
        ///VALUES
        ///  (2, &apos;John&apos;, &apos;Doe&apos;, &apos;+44 7911 123456&apos;, &apos;john.doe@example.com&apos;),
        ///  (3, &apos;Jane&apos;, &apos;Smith&apos;, &apos;+44 7911 234567&apos;, &apos;jane.smith@example.com&apos;),
        ///  (4, &apos;Alice&apos;, &apos;Johnson&apos;, &apos;+44 7911 345678&apos;, &apos;alice.johnson@example.com&apos;),
        ///  (5, &apos;Bob&apos;, &apos;Brown&apos;, &apos;+44 7911 456789&apos;, &apos;bob.brown@example.com&apos;),
        ///  (6, &apos;Charlie&apos;, &apos;Williams&apos;, &apos;+44 7911 567890&apos;, &apos;charlie.williams@example.com&apos;),
        ///  (7, &apos;David&apos;, &apos;Jone [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string example_customers_sql {
            get {
                return ResourceManager.GetString("example_customers.sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM Staff
        ///WHERE StaffID NOT IN (1, 2, 3);
        ///
        ///INSERT INTO Staff (StaffID, StaffType, Forename, Surname, PhoneNumber, Email, Password)
        ///VALUES
        ///    (4, &apos;frontdesk&apos;, &apos;Michael&apos;, &apos;Taylor&apos;, &apos;07123456789&apos;, &apos;michael.taylor@bayview.com&apos;, &apos;5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8&apos;),
        ///    (5, &apos;frontdesk&apos;, &apos;Sophia&apos;, &apos;Clark&apos;, &apos;07234567890&apos;, &apos;sophia.clark@bayview.com&apos;, &apos;5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8&apos;),
        ///    (6, &apos;frontdesk&apos;, &apos;Liam&apos;, &apos;Walker&apos;, &apos;07345678901 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string example_staff_sql {
            get {
                return ResourceManager.GetString("example_staff.sql", resourceCulture);
            }
        }
    }
}
